name: tendon_loader
description: Tendon Loader is designed to measure and help cure Achille's (uh-KILL-eez) Tendon Problems.
publish_to: 'none'
version: 1.0.0+14

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  app_settings: ^4.2.0
  archive: ^3.3.6
  cloud_firestore: ^4.4.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  firebase_ui_auth: ^1.1.13
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_svg: ^2.0.1
  go_router: ^6.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  location: ^5.0.0-dev.8
  rxdart: ^0.26.0
  syncfusion_flutter_charts: ^20.4.50
  syncfusion_flutter_xlsio: ^20.4.50-beta

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^1.1.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.svg
    - assets/enable_device.png
    - assets/enable_location.png
    - assets/enable_bluetooth.png
