name: tendon_loader
description: A bluetooth based tendon injury monitoring application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  cloud_firestore: ^1.0.4
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.0.1
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_svg: ^0.21.0+1 
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  location: ^4.1.1
  numberpicker: ^2.0.1
  path_provider: ^2.0.1
  rxdart: ^0.26.0
  syncfusion_flutter_charts: ^19.1.56
  syncfusion_flutter_xlsio: ^19.1.56-beta
  # url_launcher: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_logo.svg
    - assets/images/enable_device.png
    - assets/images/enable_location.png
    - assets/images/enable_bluetooth.png
