name: tendon_loader
description: Tendon Loader is designed to measure and help cure Achille's (uh-KILL-eez) Tendon Problems.
publish_to: 'none'
version: 1.0.0+16

environment:
  sdk: ^3.0.1

dependencies:
  app_settings: ^4.2.0
  archive: ^3.3.7
  cloud_firestore: ^4.6.0
  connectivity_plus: ^4.0.0
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.5.0
  firebase_core: ^2.11.0
  firebase_ui_auth: ^1.3.0
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_svg: ^2.0.6
  go_router: ^8.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.0
  location: ^4.4.0
  rxdart: ^0.26.0
  syncfusion_flutter_charts: ^21.2.4
  syncfusion_flutter_xlsio: ^21.2.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.0.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.svg
    - assets/enable_device.webp
    - assets/enable_location.webp
    - assets/enable_bluetooth.webp
