name: tendon_loader
description: A bluetooth based tendon injury monitoring application.
publish_to: 'none'
version: 0.0.3-preview+3

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  app_settings: ^4.1.0
  audioplayers: ^0.19.0
  cloud_firestore: ^2.2.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  hive: ^2.0.2
  intl: ^0.17.0
  location: ^4.1.1
  rxdart: ^0.26.0
  syncfusion_flutter_charts: ^19.1.56
  syncfusion_flutter_xlsio: ^19.1.56-beta

  tendon_support_lib:
    path: ../tendon_support_lib
    # git:
    #   url: https://github.com/mitulvaghamshi/tendon_support_lib.git

  tendon_support_module:
    path: ../tendon_support_module
    # git:
    #   url: https://github.com/mitulvaghamshi/tendon_support_module.git

  wakelock: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/stop.mpeg
    - assets/audio/start.mpeg
    - assets/images/enable_device.png
    - assets/images/enable_location.png
    - assets/images/enable_bluetooth.png
