name: tendon_loader
description: A bluetooth based tendon injury monitoring application.
publish_to: "none"
version: 0.0.6+6 # 

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  app_settings: ^4.1.0
  audioplayers: ^0.19.0
  cloud_firestore: ^2.2.0
  connectivity: ^3.0.3
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.0.1
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_svg: ^0.22.0
  hive: ^2.0.2
  hive_flutter: ^1.0.0
  location: ^4.1.1
  rxdart: ^0.26.0
  syncfusion_flutter_charts: ^19.1.66+1
  syncfusion_flutter_xlsio: ^19.1.66-beta
  wakelock: ^0.5.2

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/stop.mpeg
    - assets/audio/start.mpeg
    - assets/images/app_logo.svg
    - assets/images/enable_device.png
    - assets/images/enable_location.png
    - assets/images/enable_bluetooth.png
