include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    missing_required_param: error
  exclude:
    - "*.g.dart"
    - "res/**"

linter:
  rules:
    # - avoid_catching_errors
    # - avoid_annotating_with_dynamic
    # - avoid_setters_without_getters # not yet tested
    # - avoid_returning_null # there are plenty of valid reasons to return null
    # - avoid_returning_this # there are plenty of valid reasons to return this
    # - use_named_constants # not yet tested
    # - prefer_mixin # https://github.com/dart-lang/language/issues/32
    # - avoid_js_rounded_ints # only useful when targeting JS runtime
    # - avoid_double_and_int_checks # only useful when targeting JS runtime
    - avoid_types_on_closure_parameters
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_classes_with_only_static_members
    - avoid_dynamic_calls
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - deprecated_consistency
    - directives_ordering
    - flutter_style_todos
    - join_return_with_assignment
    - leading_newlines_in_multiline_strings
    - lines_longer_than_80_chars
    - missing_whitespace_between_adjacent_strings
    - no_adjacent_strings_in_list
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - sort_constructors_first
    - sort_pub_dependencies
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - unnecessary_await_in_return
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - use_if_null_to_convert_nulls_to_bools
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_raw_strings
    - use_setters_to_change_properties
