name: tendon_loader
description: Tendon Loader is designed to measure and help cure Achille's (uh-KILL-eez) Tendon Problems.
publish_to: 'none'
version: 1.0.0+17

environment:
  sdk: ^3.0.1

dependencies:
  app_settings: ^5.0.0
  archive: ^3.3.8
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_blue: ^0.8.0
  flutter_svg: ^2.0.6
  go_router: ^14.1.3
  http: ^1.1.0
  intl: ^0.19.0
  location: ^6.0.2
  rxdart: ^0.26.0 # find alternative
  syncfusion_flutter_charts: ^26.1.35
  syncfusion_flutter_xlsio: ^26.1.35

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  go_router_builder: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/enable_device.webp
    - assets/enable_location.webp
    - assets/enable_bluetooth.webp
