name: server
description: A server app for tendon_loader app.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  sqlite3: ^2.7.2

dev_dependencies:
  http: ^1.1.0
  lints: ^6.0.0
  test: ^1.24.0
