// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6gUnC93r_Y0d0Gvrj31MTnzlhHq03aFM',
    appId: '1:1041327389562:web:f96869c1dcde7d09a874c3',
    messagingSenderId: '1041327389562',
    projectId: 'tendonloader-dev',
    authDomain: 'tendonloader-dev.firebaseapp.com',
    storageBucket: 'tendonloader-dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLnRwANgTL301eif3lksZdVl49vOdSV3I',
    appId: '1:1041327389562:android:a489747d04e99cc7a874c3',
    messagingSenderId: '1041327389562',
    projectId: 'tendonloader-dev',
    storageBucket: 'tendonloader-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADd7_LxhOnxD9Tpgf1YBSaFw7mpeEgSG0',
    appId: '1:1041327389562:ios:6972799363ae77a4a874c3',
    messagingSenderId: '1041327389562',
    projectId: 'tendonloader-dev',
    storageBucket: 'tendonloader-dev.appspot.com',
    iosClientId:
        '1041327389562-fvn3rpf7spvb1oammmdluf1oth7gs732.apps.googleusercontent.com',
    iosBundleId: 'me.mitul.tendonLoader',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADd7_LxhOnxD9Tpgf1YBSaFw7mpeEgSG0',
    appId: '1:1041327389562:ios:6972799363ae77a4a874c3',
    messagingSenderId: '1041327389562',
    projectId: 'tendonloader-dev',
    storageBucket: 'tendonloader-dev.appspot.com',
    iosClientId:
        '1041327389562-fvn3rpf7spvb1oammmdluf1oth7gs732.apps.googleusercontent.com',
    iosBundleId: 'me.mitul.tendonLoader',
  );
}
