include:
  - package:lints/recommended.yaml
  - ../assets/analysis_extra.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - assets/**

linter:
  rules:
    prefer_expression_function_bodies: false
