include:
  - package:lints/recommended.yaml
  - ../../mitulvaghamshi/analysis_strict_mode.yaml

analyzer:
  exclude:
    - assets/**
    - web/**

linter:
  rules:
    prefer_expression_function_bodies: false
